# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	config.hostmanager.enabled = true
	config.hostmanager.manage_guest = true
	config.hostmanager.manage_host = false
	config.hostmanager.include_offline = false
	config.hostmanager.ignore_private_ip = true

	config.vm.define "puppetmaster" do |puppet|
		# Puppetmaster on CentOS 7
		config.vm.provider "virtualbox" do |v|
		  v.memory = 2048
		end
		puppet.vm.synced_folder ".", "/vagrant"
		puppet.vm.synced_folder "../../puppet-code", "/puppet-code"
		puppet.vm.synced_folder "../../dev-code", "/dev-code"
		puppet.vm.synced_folder "../r10k", "/r10k"
		puppet.vm.box = "boxcutter/centos72"
		puppet.vm.hostname = "puppetmaster.talentsoft.com"
		puppet.vm.network :private_network, ip: "10.0.20.10"
		#puppet.vm.network "public_network", use_dhcp_assigned_default_route: true
		puppet.vm.network "forwarded_port", guest: 8140, host: 8140
		puppet.vm.provision "shell", inline: <<-SHELL
		  sudo yum update -y
		  sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
		  sudo yum install puppetserver -y
		  sudo rm -rf /etc/puppetlabs/code
		  sudo ln -s /dev-code /etc/puppetlabs/code
		  #sudo rm -rf /etc/puppetlabs/puppetserver
		  #sudo ln -s /puppet_puppetserver /etc/puppetlabs/puppetserver
		  sudo sed -i 's/2g/512m/g' /etc/sysconfig/puppetserver
		  echo "*" | sudo tee /etc/puppetlabs/puppet/autosign.conf
			sudo /opt/puppetlabs/bin/puppetserver gem install hiera-eyaml
      sudo cp -r /vagrant/keys /etc/puppetlabs
      sudo chown puppet:puppet /etc/puppetlabs/keys/private_key.pkcs7.pem
      sudo chown puppet:puppet /etc/puppetlabs/keys/public_key.pkcs7.pem
		  sudo service puppetserver start
			sudo yum -y install git
			sudo yum -y install gem
			sudo gem install puppet_forge:2.2.6 r10k
		SHELL
		puppet.hostmanager.ip_resolver = proc do |machine|
	    result = ""
	    machine.communicate.execute("ifconfig eth1") do |type, data|
	      result << data if type == :stdout
	    end
	    (ip = /^\s*inet .*?(\d+\.\d+\.\d+\.\d+)\s+/.match(result)) && ip[1]
	  end
		puppet.hostmanager.aliases = %w(puppetmaster)
	end

	#*******************************************************************************************
	#*******************************************************************************************
	#*******************************************************************************************
	#*********************     AGENT CENTOS  ***************************************************
	#*******************************************************************************************
	#*******************************************************************************************

	config.vm.define "agent-centos" do |agent1|
		 # Puppet agent on CentOS 7
		agent1.vm.box = "boxcutter/centos72"
		agent1.vm.hostname = "agent-centos.talentsoft.com"
		agent1.vm.network :private_network, ip: "10.0.20.11"
		#agent1.vm.network "public_network", use_dhcp_assigned_default_route: true
		agent1.vm.provision "shell", inline: <<-SHELL
		  sudo yum update -y
		  sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
		  sudo yum install puppet-agent -y
		  sudo service puppet start
		SHELL
		agent1.hostmanager.ip_resolver = proc do |machine|
	    result = ""
	    machine.communicate.execute("ifconfig eth1") do |type, data|
	      result << data if type == :stdout
	    end
	    (ip = /^\s*inet .*?(\d+\.\d+\.\d+\.\d+)\s+/.match(result)) && ip[1]
	  end
		agent1.hostmanager.aliases = %w(agent-centos)
	 end

end
